---
# YAML documents begin with the document separator ---
- name: Site logins for WordPress users
  hosts: chimera
  vars_files: defaults/main.yaml
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Gather WordPress users
      tags: gathering
      block:
        - name: Capture all WordPress sites as variable urls
          ansible.builtin.command: wp site list --url={{ URL }} --path='{{ WPATH }}' --field=url
          register: urls
          changed_when: urls.rc != 0

        - name: Copy all WordPress sites to sites.txt
          ansible.builtin.copy:
            content: '{{ urls.stdout }}'
            dest: '{{ HOME }}sites.txt'
            mode: '0644'

        - name: Get all WordPress users per site
          ansible.builtin.script:
            cmd: '{{ GIT }}users.rb {{ WPATH }} {{ HOME }}'

        - name: Filter duplicate users
          ansible.builtin.script:
            cmd: '{{ GIT }}uniq.rb all-wp-users.txt filtered.txt'

        - name: Delete header rows from filtered.txt file
          ansible.builtin.lineinfile:
            path: 'filtered.txt'
            search_string: 'ID'
            state: absent
            mode: '0644'

        - name: Download the filtered.txt file
          ansible.builtin.fetch:
            src: 'filtered.txt'
            dest: '{{ GIT }}results/'
            flat: true

    - name: Build the json file
      tags: building
      block:
        - name: Run the build.rb Ruby script
          ansible.builtin.script:
            cmd: '{{ GIT }}build.rb {{ WPATH }} {{ URL }}'

        - name: Download the cooked.json file
          ansible.builtin.fetch:
            src: 'cooked.json'
            dest: '{{ GIT }}results/'
            flat: true
# Three dots indicate the end of a YAML document \],"{{ item }}":\[
...
