---
# YAML documents begin with the document separator ---
- name: Site logins for WordPress users
  hosts: chimera
  vars_files: defaults/main.yaml
  gather_facts: true
  ignore_errors: true
  vars:
    ordered: "{{ lookup('ansible.builtin.file', '{{ GIT }}results/filtered.txt') }}"
  tasks:
    - name: Gather WordPress users
      tags: gathering
      block:
        - name: List WordPress site urls
          ansible.builtin.command: wp site list --url={{ URL }} --path='{{ WPATH }}' --field=url
          register: urls
          changed_when: urls.rc != 0

        - name: Write urls to sites.txt
          ansible.builtin.copy:
            content: '{{ urls.stdout }}'
            dest: '{{ HOME }}sites.txt'
            mode: '0644'

        - name: Get all WordPress users per site
          ansible.builtin.script:
            cmd: '{{ GIT }}users.rb {{ WPATH }} {{ HOME }}'

        - name: Filter duplicate users
          ansible.builtin.script:
            cmd: '{{ GIT }}uniq.rb all-wp-users.txt filtered.txt'

        - name: Download filtered.txt
          ansible.builtin.fetch:
            src: 'filtered.txt'
            dest: '{{ GIT }}results/'
            flat: true

        - name: Write sorted IDs
          ansible.builtin.copy:
            content: '{{ ordered }}'
            dest: '{{ HOME }}ordered.txt'
            mode: '0644'

        - name: Download ordered.txt
          ansible.builtin.fetch:
            src: 'ordered.txt'
            dest: '{{ GIT }}results/'
            flat: true

    - name: Build the json file
      tags: building
      block:
        - name: Compile the user:site index
          ansible.builtin.script:
            cmd: '{{ GIT }}build.rb {{ WPATH }} {{ URL }}'

        - name: Download cooked.json
          ansible.builtin.fetch:
            src: 'cooked.json'
            dest: '{{ GIT }}results/'
            flat: true
# Three dots indicate the end of a YAML document
...
