---
- name: Site logins for WordPress users
  hosts: chimera
  vars_files: defaults/main.yaml
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Compile all WordPress users
      tags: gather
      block:
        - name: Get site list
          ansible.builtin.command: wp site list --url={{ URL }} --path='{{ WPATH }}' --field=url
          register: urls
          changed_when: urls.rc != 0

        - name: Write site urls to sites.txt
          ansible.builtin.copy:
            content: '{{ urls.stdout }}'
            dest: 'sites.txt'
            mode: '0644'

        - name: Query users per site
          ansible.builtin.script:
            cmd: '{{ GIT }}users.rb {{ WPATH }} {{ HOME }}'

        - name: Filter duplicate users
          ansible.builtin.script:
            cmd: "{{ GIT }}uniq.rb all-ids.txt filtered-ids.txt"

    - name: Build the reference files
      tags: build
      block:
        - name: Compile the user-site index
          ansible.builtin.script:
            cmd: '{{ GIT }}build.rb {{ WPATH }} {{ URL }}'

        - name: Download the reference files
          ansible.builtin.fetch:
            src: '{{ item }}'
            dest: '{{ GIT }}results/'
            flat: true
          loop:
            - 'zeros.json'
            - 'current.json'

    - name: Delete obsolete users from WordPress
      tags: remove
      block:
        - name: Remove designated users
          ansible.builtin.script:
            cmd: '{{ GIT }}remove.rb {{ WPATH }} {{ URL }}'
...
